### PR TITLE
update: add support for `pre-commit`

### PR DESCRIPTION
**Pull request by synchon**
* [x] description of feature/fix
* [x] tests added/passed
* [x] add an entry for the latest changes

This PR adds support for `pre-commit` in the codebase and makes necessary changes to adopt it.

### CODE REVIEW

**Comment by fraimondo** [comment]
can you explain what's the goal behind this PR?

**Comment by synchon** [comment]
> can you explain what's the goal behind this PR?

It enables the use of [Git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) specifically `pre-commit` via https://pre-commit.com . The pre-commit checks include everything from spellcheck to linting thus reducing the need for separate lint or spell-check commits and making contribution easy.

**Comment by fraimondo** [comment]
Is this _optional_? Or it will not allow to commit if something is off?

**Comment by synchon** [comment]
> Is this _optional_? Or it will not allow to commit if something is off?

Once you do `pre-commit install`, it becomes mandatory. If you want to bypass a commit, you need to pass `--no-verify` flag to `git commit`. The docs include the instructions.

**Comment by fraimondo** [comment]
perfect!

Fix conflicts and LGTM

**Pull request merged**
