### PR TITLE
[DOC]: Fill in built-in coordinates list

### PR DESCRIPTION
**Pull request by synchon**
### Which element of the documentation do you want to modify and why?

Like Parcellations (https://juaml.github.io/junifer/main/builtin.html) but for Coordinates

### Anything else to say?

_No response_

### CODE REVIEW

**Comment by synchon** [comment]
We need to anyway update the list later. For now, it has as much information we have available.

**Comment by synchon** [comment]
> @synchon We have 15 coordinates in the `VOIs/meta` directory, why only 9 in the available and 3 in the planned?
> 
> They are all available, problem is that we don't have the right documentation?

Yes, exactly.

**Comment by fraimondo** [comment]
Or either we:

1. Remove for the moment
2. Add in the doc that we don't have the details yet.

**Comment by synchon** [comment]
> Or either we:
> 
> 1. Remove for the moment
> 2. Add in the doc that we don't have the details yet.

2. sounds good to me.

**Comment by synchon** [comment]
I have added as much as I can with some more info.

**Review by fraimondo — APPROVED** [review]

**Pull request merged**
