### PR TITLE
[ENH]: Introduce new `cli` sub-package

### PR DESCRIPTION
**Pull request by synchon**
* [x] description of feature/fix
* [x] tests added/passed
* [x] add an entry for the latest changes

This PR refactors the CLI components and splits the `api` sub-package into a new `cli` sub-package for improved intent and maintenance. It also reduces the side-effects introduced by CLI components, leaking into the public API components and plays well with lazy imports.

### CODE REVIEW

**Comment by fraimondo** [comment]
I like what this PR is doing, but I think we are still failing to do it properly (same mistake as before).

The `cli` module should take care of click and all the command-line-interface parsing stuff.
The `api` module is the application programming interface module. 

The first module should parse/interpret the cli commands and call the second module, which is the one available for the user in case they decide to write python code to use junifer.

**Comment by synchon** [comment]
> I like what this PR is doing, but I think we are still failing to do it properly (same mistake as before).
> 
> The `cli` module should take care of click and all the command-line-interface parsing stuff. The `api` module is the application programming interface module.
> 
> The first module should parse/interpret the cli commands and call the second module, which is the one available for the user in case they decide to write python code to use junifer.

I see what you mean, makes sense to me. I didn't wanna change a lot of stuff before an initial review so will make the further changes now.

**Comment by fraimondo** [comment]
> > I like what this PR is doing, but I think we are still failing to do it properly (same mistake as before).
> > The `cli` module should take care of click and all the command-line-interface parsing stuff. The `api` module is the application programming interface module.
> > The first module should parse/interpret the cli commands and call the second module, which is the one available for the user in case they decide to write python code to use junifer.
> 
> I see what you mean, makes sense to me. I didn't wanna change a lot of stuff before an initial review so will make the further changes now.

It was my original intention, but things got too mixed.

**Comment by synchon** [comment]
> > > I like what this PR is doing, but I think we are still failing to do it properly (same mistake as before).
> > > The `cli` module should take care of click and all the command-line-interface parsing stuff. The `api` module is the application programming interface module.
> > > The first module should parse/interpret the cli commands and call the second module, which is the one available for the user in case they decide to write python code to use junifer.
> > 
> > 
> > I see what you mean, makes sense to me. I didn't wanna change a lot of stuff before an initial review so will make the further changes now.
> 
> It was my original intention, but things got too mixed.

There, should be cleaner now. Good for review.

**Review by fraimondo — APPROVED** [review]

**Pull request merged**
